= Asciidoctor Plantuml Extension

:antora-link: https://antora.org[Antora]

Port of `Ruby` based https://github.com/hsanson/asciidoctor-plantuml[Asciidoctor Plantuml Extension] to `JavaScript` and https://github.com/asciidoctor/asciidoctor.js[Asciidoctor.js].

== Development status
ifdef::env-github[]
image:https://travis-ci.org/eshepelyuk/asciidoctor-plantuml.js.svg?branch=master["Travis Build Status", link="https://travis-ci.org/eshepelyuk/asciidoctor-plantuml.js"
]
endif::[]

== Overview

The extension tries to mimic behaviour of `[plantuml]` block from https://asciidoctor.org/docs/asciidoctor-diagram[Asciidoctor Diagram].

Unlike original code, it uses https://github.com/plantuml/plantuml-server[PlantUML server] for displaying images.
Inside `image` tags produced by the extension the `src` attribute contains a link to PlantUML server.

During page rendering diagram is generated on PlantUML Server and displayed by browser.

== Asciidoctor.js integration

Sample code

[source,javascript]
....
const asciidoctor = require('asciidoctor.js')();
const plantuml = require("asciidoctor-plantuml"); <1>

const ADOC = `
== PlantUML
:plantuml-server-url: http://plantuml.org/plantuml <2>
[plantuml]
----
alice -> bob
bob ..> alice
----
`;

plantuml.register(asciidoctor.Extensions);
console.log(asciidoctor.convert(ADOC)); <3>

const registry = asciidoctor.Extensions.create();
plantuml.register(registry);
console.log(asciidoctor.convert(ADOC, {'extension_registry': registry})); <4>

....
<1> `npm install asciidoctor-plantuml` must be called before importing.
<2> it's possible to configure different URL for PlantUML server using Asciidoctor attribute.
<3> using global extension registry
<4> with custom registry

Regardless of global or custom registry usage, produced HTML output will look like

[source,html]
----
<div class="sect1">
<h2 id="_plantuml">PlantUML</h2>
<div class="sectionbody">
<div class="imageblock"><div class="content"><img class="plantuml" src="http://plantuml.org/plantuml/png/Iyp9J4vLqBLJICfFuW9Y1JqzEuL4a200"/></div></div>
</div>
</div>
----

== Antora integration

Integration is just the matter of enabling the extension in https://docs.antora.org/antora/1.0/playbook/playbook/[site playbook]
and providing address of PlantUML server.

There's sample https://github.com/eshepelyuk/asciidoctor-plantuml-antora[Antora component] demonstrating usage of this extension.
Below are the steps to build and run sample Antora site with PlantUML diagrams support.

. Create directory for Antora playbook

  $ mkdir plantuml-antora
  $ cd plantuml-antora

. Install required modules

  $ npm i -g @antora/cli
  $ npm i -g @antora/site-generator-default
  $ npm i asciidoctor-plantuml
  $ npm i -g serve

. Create Antora playbook
+
.site.yml
[source,yaml]
----
site:
  title: Antora Demo Site
  start_page: asciidoctor-plantuml-antora::index.adoc
content:
  sources:
  - url: https://github.com/eshepelyuk/asciidoctor-plantuml-antora.git
    branches: master
ui:
  bundle: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
asciidoc:
  extensions:
    - asciidoctor-plantuml <1>
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml' <2>
output:
  dir: build
----
<1> enable Asciidoctor PlantUML extension
<2> use public PlantUML Server

. Generate site

  $ antora generate site.yml

. Start web server

  $ serve build

. Check results

Open http://localhost:5000 in browser.