= Asciidoctor Plantuml Extension
:plantuml-server-public: http://www.plantuml.com/plantuml
:antora-link: https://antora.org[Antora]
:toc:

Port of `Ruby` based https://github.com/hsanson/asciidoctor-plantuml[Asciidoctor Plantuml Extension] to `JavaScript` and https://github.com/asciidoctor/asciidoctor.js[Asciidoctor.js].

== Project status
ifdef::env-github[]
image:https://travis-ci.org/eshepelyuk/asciidoctor-plantuml.js.svg?branch=master["Travis Build Status", link="https://travis-ci.org/eshepelyuk/asciidoctor-plantuml.js"
]
endif::[]

== Overview

The extension tries to mimic behaviour of `[plantuml]` block from https://asciidoctor.org/docs/asciidoctor-diagram[Asciidoctor Diagram].

Unlike original code, it uses https://github.com/plantuml/plantuml-server[PlantUML server] for displaying images.
Inside `image` tags produced by the extension the `src` attribute contains a link to PlantUML server.

During page rendering diagram is generated on PlantUML Server and displayed in browser.

=== Extension installation

  $ npm i asciidoctor-plantuml

=== PlantUML server

https://github.com/plantuml/plantuml-server[PlantUML server] is a standalone web application exposing HTTP API that allows generating diagram images on the fly.

It can be used in two modes

* Public instance, for example this one {plantuml-server-public}.
* For performance reason it's recommended to use private one.
+
One could easily deploy it as Docker container as described in https://github.com/plantuml/plantuml-server#how-to-run-the-server-with-docker[README].

  $ docker run -d -p 8080:8080 plantuml/plantuml-server:jetty

=== Configuration

Configuration can be provided via http://asciidoctor.org/docs/user-manual/#attributes[Asciidoctor attributes].


.Supported configuration attributes
|===
|Attribute |Description

|plantuml-server-url
|URL of PlantUML Server instance, that will be used for generating diagrams. E.g. http://www.plantuml.com/plantuml

|plantuml-fetch-diagram
|If set, images will be downloaded and saved to local folder. `img` tags will be pointing to local folder.
Otherwise, `img` tags will have `src` attribute pointing to `:plantuml-server-url:`

|imagesoutdir
|Analogue of https://asciidoctor.org/docs/asciidoctor-diagram/#image-output-location[Asciidoctor Diagram] attribute.
E.g. `./assets/images`
|===

== Antora integration

Integration is just the matter of enabling the extension in https://docs.antora.org/antora/1.0/playbook/playbook/[site playbook]
and providing address of PlantUML server.

I've created sample https://github.com/eshepelyuk/asciidoctor-plantuml-antora[Antora component] demonstrating usage of this extension.
Below are the steps to build and run sample site with PlantUML support.

. Create directory for Antora playbook

  $ mkdir plantuml-antora
  $ cd plantuml-antora

. Install additional modules required for this sample

  $ npm i -g @antora/cli
  $ npm i -g @antora/site-generator-default
  $ npm i -g serve

. Create Antora playbook
+
.site.yml
[source,yaml]
[subs="verbatim,attributes"]
----
site:
  title: Antora Demo Site
  start_page: asciidoctor-plantuml-antora::index.adoc
content:
  sources:
  - url: https://github.com/eshepelyuk/asciidoctor-plantuml-antora.git
    branches: master
ui:
  bundle: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
asciidoc:
  extensions:
    - asciidoctor-plantuml <1>
  attributes:
    plantuml-server-url: '{plantuml-server-public}' <2>
output:
  dir: build
----
<1> enable Asciidoctor PlantUML extension
<2> use public PlantUML Server

. Generate site

  $ antora generate site.yml

. Start web server

  $ serve build

. Check results

Open http://localhost:5000 in browser.

== Asciidoctor.js integration

Sample code

[source,javascript]
[subs="verbatim,attributes"]
....
const asciidoctor = require('asciidoctor.js')();
const plantuml = require("asciidoctor-plantuml");

const ADOC = `
== PlantUML
:plantuml-server-url: {plantuml-server-public} <1>
[plantuml]
----
alice -> bob
bob ..> alice
----
`;

plantuml.register(asciidoctor.Extensions);
console.log(asciidoctor.convert(ADOC)); <2>

const registry = asciidoctor.Extensions.create();
plantuml.register(registry);
console.log(asciidoctor.convert(ADOC, {'extension_registry': registry})); <3>

....
<1> it's possible to configure different URL for PlantUML server using Asciidoctor attribute.
<2> usage with global extension registry
<3> usage with custom registry

Regardless of global or custom registry usage, produced HTML output will look like

[source,html]
[subs="verbatim,attributes"]
----
<div class="sect1">
<h2 id="_plantuml">PlantUML</h2>
<div class="sectionbody">
<div class="imageblock"><div class="content"><img class="plantuml" src="{plantuml-server-public}/png/Iyp9J4vLqBLJICfFuW9Y1JqzEuL4a200"/></div></div>
</div>
</div>
----
