= Asciidoctor Plantuml Extension
:toc:
Port of https://github.com/hsanson/asciidoctor-plantuml[Asciidoctor Plantuml Extension] to https://github.com/asciidoctor/asciidoctor.js[Asciidoctor.js].

== Development status
ifdef::env-github[]
image:https://travis-ci.org/eshepelyuk/asciidoctor-plantuml.js.svg?branch=master["Travis Build Status", link="https://travis-ci.org/eshepelyuk/asciidoctor-plantuml.js"
]
endif::[]

== Overview

The extension tries to mimic behaviour of `[plantuml]` block from https://asciidoctor.org/docs/asciidoctor-diagram[Asciidoctor Diagram].

Unlike original code, it uses https://github.com/plantuml/plantuml-server[PlantUML server] for displaying images.
Inside `image` tags produced by the extension the `src` attribute contains a link to PlantUML server.

During page rendering diagram is generated on PlantUML Server and displayed by browser.

== Asciidoctor.js integration

Sample code

[source,javascript]
....
const asciidoctor = require('asciidoctor.js')();
const plantuml = require("asciidoctor-plantuml"); <1>

const ADOC = `
== PlantUML
:plantuml-server-url: http://plantuml.org/plantuml <2>
[plantuml]
----
alice -> bob
bob ..> alice
----
`;

plantuml.register(asciidoctor.Extensions);
console.log(asciidoctor.convert(ADOC)); <3>

const registry = asciidoctor.Extensions.create();
plantuml.register(registry);
console.log(asciidoctor.convert(ADOC, {'extension_registry': registry})); <4>

....
<1> `npm install asciidoctor-plantuml` must be called before importing.
<2> it's possible to configure different URL for PlantUML server using Asciidoctor attribute.
<3> using global extension registry
<4> with custom registry

Regardless of global or custom registry usage, produced HTML output will look like

[source,html]
----
<div class="sect1">
<h2 id="_plantuml">PlantUML</h2>
<div class="sectionbody">
<div class="imageblock"><div class="content"><img class="plantuml" src="http://plantuml.org/plantuml/png/Iyp9J4vLqBLJICfFuW9Y1JqzEuL4a200"/></div></div>
</div>
</div>
----

== Antora integration

TBD

// Main intention to provide http://plantuml.com/[PlantUML] support for https://antora.org[Antora].
